### ISSUE TITLE
Disable credential persisting for `actions/checkout`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1859]
It seems that the default behavior of `persist-credentials:true` is generally a security issue (https://github.com/actions/checkout/issues/485). We should be disabling it in all of our workflows. Some jobs might fail if they were depending on this persisted value. The solution would be to define it in the job's environment, e.g.:
```yaml
- name: Do something
  run: echo something
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
```

For more info, take a look at #1848 where this problem was found.
