### ISSUE TITLE
Build Sway projects at every CI run

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#233]
We install `forc` during the build steps and start building the contracts 
```
      - name: Install Forc
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: forc --version 0.11.0

      - name: Build Sway Examples
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin build-test-projects
```
see https://github.com/FuelLabs/fuels-rs/pull/234/files
