### ISSUE TITLE
Docker Compose won't run on Linux without privileged access

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#265]
When a Linux user runs the `services:run` command mentioned in the README to run the Docker container using `docker compose`, it will fail due to OS restrictions.

The error message printed is:
```
thread 'main' panicked at 'OS can't spawn a new worker thread: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:291:14
```

The workaround for now is to either run that service on bare metal or run it as a privileged process using additional parameters in the `docker-compose.yml`, adding `privileged: true` under the `fuel-core` service:

```
version: "3"

services:
  fuel-core:
    build: ./services/fuel-core
    privileged: true
    ports:
      - "4000:4000"
    volumes:
      - fuel-core-db:/mnt/db
volumes:
  fuel-core-db:
```
